title: Home
theme: minimal-mistakes-jekyll

minima:
  # Enables navigation bar links for pages
  navigation:
    - title: "Home"
      url: "/"
    - title: "About"
      url: "/about/"
    - title: "Projects"
      url: "/projects/"
    - title: "Blog"
      url: "/blog/"
    - title: "Contact"
      url: "/contact/"
